module.exports = Object.freeze({
    "#PL_FIRINGRANGE-ALONE": "Fucking Around in the Firing Range",
    "#PL_FIRINGRANGE-PARTY": "Doing Random Shit with Friends in the Firing Range",
    "#RICHPRESENCE_PARTY_LOBBY_N_N": "Waiting to Die Another Match...",
    "#RICHPRESENCE_PARTY_LOBBY": "Waiting to Die Another Match...",
    "#PL_TRIO": "TRIOS-The 3 Stooges",
    "#PL_DUO": "DUOS-Cause 2 is Better Than 1 (Wrong)",
    "#PL_Ranked_Leagues": "RANKED-Your Teammates are Probably Ass",
    "#GAMEMODE_ARENAS": "ARENAS",
    "#GAMEMODE_ARENAS_RANKED": "RANKED ARENAS",
    "#PL_TRAINING": "In the training",
    "#LOADINGSCREEN": "Oh Boy Here we go Again...",
    "#MAINMENU": "At Main Menu, Probably AFK",
    "#mp_rr_canyonlands_mu2": "Kings Canyon",
    "#mp_rr_canyonlands_mu1_classic_desc": "Kings Canyon",
    "#mp_rr_canyonlands_mu3": "Kings Canyon",
    "#mp_rr_canyonlands_staging": "The Firing Range",
    "#mp_rr_canyonlands_staging_desc": "The Firing Range",
    "#mp_rr_canyonlands_mu1_night": "Shadow Royale",
    "#mp_rr_canyonlands_mu1_night_desc": "Shadow Royale",
    "#mp_rr_desertlands_holiday": "Winter Express",
    "#mp_rr_desertlands_holiday_desc": "Winter Express",
    "#mp_rr_desertlands_64k_x_64k": "World's Edge",
    "#mp_rr_desertlands_64k_x_64k_tt": "World's Edge",
    "#mp_rr_desertlands_mu1": "World's Edge",
    "#mp_rr_desertlands_mu1_desc": "World's Edge",
    "#mp_rr_desertlands_mu2": "World's Edge",
    "#mp_rr_desertlands_mu2_desc": "World's Edge",
    "#mp_rr_desertlands_mu3": "World's Edge",
    "#mp_rr_desertlands_mu3_desc": "World's Edge",
    "#mp_rr_olympus": "Olympus",
    "#mp_rr_olympus_desc": "Olympus",
    "#mp_rr_olympus_mu1": "Olympus",
    "#mp_rr_olympus__mu1_desc": "Olympus",
    "#mp_rr_tropic_island": "Shit Point",
    "#mp_rr_arena_phase_runner": "Phase Runner",
    "#mp_rr_arena_phase_runner_desc": "Phase Runner",
    "#mp_rr_party_crasher": "Party Crasher",
    "#mp_rr_party_crasher_desc": "Party Crasher",
    "#mp_rr_aqueduct": "Overflow",
    "#mp_rr_aqueduct_desc": "Overflow",
    "#mp_rr_arena_skygarden": "Encore"
});